// generate-name.ts

// generated by chatgpt
const catNames = [
  "Bella",
  "Bubbles",
  "Buttercup",
  "Caramel Swirl",
  "Charlie",
  "Cinnamon Swirl",
  "Cocoa Puff",
  "Cotton Ball",
  "Cuddles",
  "Cupcake",
  "Daisy",
  "Doodles",
  "Fluffy Boy",
  "Fluffy Whiskers",
  "Giggles",
  "Ginger Snap",
  "Golden Paws",
  "Jellybean",
  "Jellybean Toes",
  "Kitty",
  "Licorice Lace",
  "Lucky Charm",
  "Lucy",
  "Luna",
  "Marshmallow Cloud",
  "Max",
  "Milo",
  "Misty Shadow",
  "Mittens",
  "Molly",
  "Moonlight Sonata",
  "Muffin",
  "Noodles",
  "Oliver",
  "Peaches",
  "Pebbles",
  "Peppermint Twist",
  "Popsicle",
  "Pumpkin",
  "Pumpkin Spice",
  "Shadow",
  "Silent Whisper",
  "Silver Lining",
  "Simba",
  "Smokey",
  "Snowball",
  "Snuggles",
  "Sparkles",
  "Sprinkles",
  "Squiggles",
  "Sunny Delight",
  "Tiger",
  "Tigger",
  "Twilight Sparkle",
  "Twinkles",
  "Velvet Purr",
  "Waffle",
  "Whiskers",
  "Wiggles"
];

const colors = [
  "#2857b7",
  "#8941cd",
  "#893863",
  "#f1520a",
  "#d70d8a",
  "#1c8cf0",
  "#bde646",
  "#9f1ab0",
  "#0c23ea",
  "#07829f",
  "#2997f9",
  "#3a15d1",
  "#4144c5",
  "#08682d",
  "#c4451a",
  "#be50a5",
  "#a0640c",
  "#5371ce",
  "#0c07ca",
  "#ce8e0e"
];

export const randomCatName = () => {
  const randomIndex = Math.floor(Math.random() * catNames.length);
  return catNames[randomIndex];
};

export const randomColor = () => {
  const randomIndex = Math.floor(Math.random() * colors.length);
  return colors[randomIndex];
};
